#!/bin/bash
#CONF_FILE=/etc/mpd_wc/mpd_wc.conf
CONF_FILE=debian/etc/mpd_wc.conf
source ${CONF_FILE}

SERVICE="MPD WebClient"
ARGS="start ${CONF_FILE}"

do_start() { 
  start-stop-daemon -T --pidfile ${PIDFILE} && { echo "${SERVICE} already running." ; return 1 ; }
  echo "Starting ${SERVICE}"
  [ -d ${PIDFOLDER} ] || { mkdir -p "${PIDFOLDER}" ; chown "${USER}:${GROUP}" "${PIDFOLDER}" ; }
  start-stop-daemon -b --start --user $USER --group $GROUP --chuid $USER --exec "${SERVICE_BIN}" ${ARGS}
}

do_stop() {
  start-stop-daemon -T --pidfile ${PIDFILE} || { echo "${SERVICE} not running." ; return 1 ; }
  echo "Stopping ${SERVICE}"
  start-stop-daemon -K --pidfile ${PIDFILE} 
  rm ${PIDFILE}
}

### main logic ###
case "$1" in
  start)
        do_start
	exit $?
        ;;
  stop)
        do_stop
	exit $?
        ;;
  status)
        # TODO - check if process is actually running or if it's just a dangling pidfile.
        [ -f ${PIDFILE} ] && echo "Running" || echo "Not running"
        ;;
  restart|reload|condrestart)
        do_stop
        do_start
	exit $?
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
