#!/bin/bash
#CONF_FILE=/etc/mpd_wc/mpd_wc.conf
CONF_FILE=/home/kavi/projects/flask/mpdhttp/debian/etc/mpd_wc.conf
source ${CONF_FILE}

SERVICE="MPD WebClient"
ARGS="start ${CONF_FILE}"

do_start() { 
  start-stop-daemon -T --pidfile ${PIDFILE} && { echo "${SERVICE} already running." ; exit 1 ; }
  echo "Starting ${SERVICE}"
  start-stop-daemon -b --start --user $USER --group $GROUP --chuid $USER --exec "${SERVICE_BIN}" ${ARGS} || echo "Failed to start"
  [ -f ${PIDFILE} ] && echo "MPD WebClient started." 
}

do_stop() {
  echo "Stopping ${SERVICE}"
  start-stop-daemon -K --pidfile ${PIDFILE} 
  rm ${PIDFILE}
}

### main logic ###
case "$1" in
  start)
        do_start
        ;;
  stop)
        do_stop
        ;;
  status)
        # TODO - check if process is actually running or if it's just a dangling pidfile.
        [ -f ${PIDFILE} ] && echo "Running" || echo "Not running"
        ;;
  restart|reload|condrestart)
        do_stop
        do_start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
